library(shiny)
library(BiocManager)
library(Seurat)
library(RColorBrewer)
library(ggplot2)
library(multtest)
library(biomaRt)
library(AnnotationHub)
library(clusterProfiler)
library(dplyr)
library(magrittr)
library(org.Hs.eg.db)
library(org.Mm.eg.db) 
library(plotly)
library(mailR)
#options("repos" = c(CRAN="https://mirrors.tuna.tsinghua.edu.cn/CRAN/"))
#options(encoding = "UTF-8")
#rsconnect::deployApp('scsweb')